all:
	gcc BMASSE-1D.c -o BMASSE-1D -m64 -mfpmath=sse -O3 -ffast-math -march=native -msse2
	gcc BMASSE-4D.c -o BMASSE-4D -m64 -mfpmath=sse -O3 -ffast-math -march=native -msse2
	gcc BMASSE-1D-Serial.c -o BMASSE-1D-Serial -m64 -mfpmath=sse -O3 -ffast-math -march=native -msse2


